module Whack
  LAYER_ORDER_SUB_BACKGROUND = -1
  LAYER_ORDER_BACKGROUND = 0
  LAYER_ORDER_LOW = 3
  LAYER_ORDER_MAIN = 5
  LAYER_ORDER_HIGH = 7
  LAYER_ORDER_HUD = 10
  LAYER_ORDER_UI_OVERLAY = 100
  LAYER_ORDER_SYSTEM_OVERLAY = 1000
end
